services:
  backend:
    build: ./server
    ports:
      - '8000:8000'
    networks:
      - mern_network
    environment:
      MONGO_URL: mongodb://localhost:27017/nasadatabase
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - '3000:3000'
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://localhost:8000/v1

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
